---
kind: pipeline
type: docker
name: default

steps:
- name: Test
  image: golang:1.15-alpine
  commands:
  - go vet ./...
  - go test -race -cover -coverprofile=c.out -covermode atomic ./...
  - go tool cover -func=c.out | tee func.txt

- name: Report
  image: xuu0/alpine_jq_httpie
  environment:
    SECRET:
      from_secret: secret
  commands:
  -	./coverage.sh func.txt
...